# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-30 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
