# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-30 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20180630_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
