# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-01 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20180630_1117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=set([('event', 'phone')]),
        ),
    ]
